---
driver:
  name: vagrant

  chef_version: latest
  ports:
  - 4443:443/tcp
  - 8888:80/tcp

driver_config:
  vagrantfiles:
  - vagrant_additional_config.rb

# transport:
#  name: dokken

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian/wheezy64
- name: ubuntu-16.04
- name: ubuntu-17.04
  driver:
    image: dokken/ubuntu-17.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd

suites:
- name: default
  run_list:
  - recipe[chef_wordpress::default]
  encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
