language: ruby
cache: bundler

sudo: required
dist: trusty

group: edge

git:
  depth: 50

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

services: docker

env:
  matrix:
#  - INSTANCE=default-amazonlinux
#  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-9
#  - INSTANCE=default-centos-5
#  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-fedora-25
  - INSTANCE=default-fedora-26
  - INSTANCE=default-fedora-latest
#  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1704
#  - INSTANCE=default-opensuse-leap

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version

script:
- KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
  - script:
    - chef exec delivery local all
    env: UNIT_AND_LINT=1
